services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "30000:30000"
    restart: unless-stopped
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "30001:30001"
    restart: unless-stopped
    networks: 
      - app-network
    depends_on:
      - backend

volumes:
  mongo-data:

networks:
  app-network: