services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network
  
  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks: 
      - app-network
    depends_on:
      - backend

volumes:
  mongo-data:

networks:
  app-network: